### ISSUE TITLE
Add Donation not working

### ISSUE THREAD

**Issue by nitiresources** [technofreaky/woocomerce-quick-donation#10]
Just installed, added project and attempt donation but no redirection and no donation at backend. It appears this error caused it. Warning: array_merge(): Argument #1 is not an array in /home/*****/public_html/wp-content/plugins/woocommerce-quick-donation/includes/admin/wps/settings.php on line 148

**Comment by technofreaky** [comment]
Hi,

I have fixed the issue. kindly download the latest source from github

Github : https://github.com/technofreaky/woocomerce-quick-donation/tree/WCQD-V2.0---3.0

Download Link : https://github.com/technofreaky/woocomerce-quick-donation/archive/WCQD-V2.0---3.0.zip
