### ISSUE TITLE
Unable to overwrite template

### ISSUE THREAD

**Issue by iwakun** [technofreaky/woocomerce-quick-donation#12]
I've created a 'donation-form.php' and placed it in the 'mytheme/woocommerce/donation' folder. However, the plugin still uses the generic template.

I think the error is somewhere in the class-quick-donation-functions.php file around line 155 in the 'wc_locate_template' function. If I echo $template_full_path on the first line, it's the custom template file, but when I echo it out before the return, it's the default template file.

It looks like it will use the default if the template name is found in the 'general' section. Not sure why you want to do this, but I think that's what is happening.

**Comment by technofreaky** [comment]
Hi,

Thanks for reporting will change and update you

**Comment by ierpe** [comment]
+1 same problem here...

**Comment by technofreaky** [comment]
@ierpe 

today i will check and update . :)

**Comment by technofreaky** [comment]
Hi,

Kindly go to 
` plugins/woocommerce-quick-donation/includes/class-quick-donation-functions.php ` on line **42**
you will find a line with the same code `add_filter( 'woocommerce_locate_template' , array($this,'wc_locate_template'),10,3);` kindly come it. for now. i will release it with other bug fix by today or tomorrow

**Comment by ierpe** [comment]
Still not working for me. If I echo ``` $locate ``` in the function ```locate_template``` line 147, I get : 
```
/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/fields/field-select.php
/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/fields/field-text.php
/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/donation-form.php
```

I am using the [BedRock stack](https://roots.io/bedrock/) , maybe that has something to do with it?
It seems that it does not reach the woocommerce folder in my theme...

**Comment by technofreaky** [comment]
@ierpe  can you please download the unreleased version of this plugin and check
Download link : http://varunsridharan.in/woocommerce-quick-donation.zip

**Comment by ierpe** [comment]
Hi, how are you today? :)


I tried with this version but same thing...

When I echo $locate from line 178 in class-quick-donation-functions.php, I
still get :

/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/fields/field-select.php
/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/fields/field-text.php
/home/piero/www/bicewp/web/app/plugins/woocommerce-quick-donation/template/donation-form.php

Just to be sure I'm doing things right... my custom form template is in :

/web/app/themes/BICE/woocommerce/donation/donation_form.php

While BICE is the theme I'm currently working on.
Is that correct?

Pierre


On 21 October 2015 at 12:03, Varun Sridharan <notifications@github.com>
wrote:

> @ierpe <https://github.com/ierpe> can you please download the unreleased
> version of this plugin and check
> Download link : http://varunsridharan.in/woocommerce-quick-donation.zip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/technofreaky/woocomerce-quick-donation/issues/12#issuecomment-149844060>
> .
>



-- 
Pierre

**Comment by technofreaky** [comment]
No,

i have updated the code but not changed the version

**Comment by technofreaky** [comment]
note that its not `donation_form.php` its `donation-form.php`

**Comment by ierpe** [comment]
haaa! It's working now... it's weird because I'm pretty sure I copied the file from the template folder... It's working, even with the last github version

**Comment by technofreaky** [comment]
ho nice

kindly use the version which i gave using download link . soon i will release it in wp plugin directory

**Comment by ierpe** [comment]
ok!
