### ISSUE TITLE
order details

### ISSUE THREAD

**Issue by macra** [technofreaky/woocomerce-quick-donation#13]
On the edit order page in the 'Order Items' section It only shows the title of the single donation product.
![screen shot 2015-10-19 at 11 35 48 am](https://cloud.githubusercontent.com/assets/2403454/10567087/fe222e94-7655-11e5-9c22-b3f21844f15d.png)
It does show within the meta-data the project ID and is_donation variable, but not the project title.
This is rather inconvenient, as it isn't easy to determine which project has which ID. I need to have the project title listed with the meta data rather than, or additional to the project ID value. I think this will enhance what is an excellent plugin. 
This issue is critical for me to resolve as I have a client that has a large number of different donation projects, and I need to resolve this as soon as possible. 
Many Thanks,
Craig.

**Comment by technofreaky** [comment]
Hi,
Sure will fix it. currently working on modifying the order page for donation order in next 2 days it will be fixed

**Comment by macra** [comment]
The fix is perfect, good work. I have discovered some other issues with the update however. Added here as new issues.
