### ISSUE TITLE
WooCommerce Donation Product Not Exist

### ISSUE THREAD

**Issue by ierpe** [technofreaky/woocomerce-quick-donation#16]
Hey,

I don't know why this happened, and I do not find how I can recreate the donation product. I went into the Quick Donation settings but...
Deactivating / Reactivating the plugin did not solve the problem... any suggestion?

**Comment by technofreaky** [comment]
@ierpe 
New Option Added To SELF Check and create donation product via system tools page in WooCommerce Quick Donation System Tool Page
