### ISSUE TITLE
WCQD V2.0 Features Info

### ISSUE THREAD

**Issue by technofreaky** [technofreaky/woocomerce-quick-donation#2]
### Admin Side Features
- [x] Separate Page for donation order listing
- [ ] Separate page for donation order reports
- [x] Hide donation orders from woo commerce listing
- [x] Bubble notification in order listing page

### Site Side Features
- [x] Minimum Donation Amount
- [x] Maximum Donation Amount
- [x] Use Defined Custom Error Message
- [ ] Donation Form Widgets
- [ ] Donation Project With Goal / Target

### WordPress Side
- [ ] Support For Multi Site.

**Comment by kkotha82** [comment]
I am looking for a partial recurring feature. In the widget along with donated to project and donation amount, we capture whether it is recurring(yes/no), and if yes, the frequency(monthly,quarterly,half-yearly,yearly). Once a donation is made, the plugin reminds the donor one day before recurring due date, and again on the due date. The actual donation itself the user will do manually.

Can you build such a feature? Attached is a workflow for your reference.
![screen shot 2015-10-25 at 6 01 05 pm](https://cloud.githubusercontent.com/assets/15326217/10736550/a7bbac9a-7c33-11e5-9a1a-d947b58371e8.png)

**Comment by kkotha82** [comment]
The donation 'project name' is not the same as WooCommerce 'product name'. I am using a plugin for generating PDF invoices. Is there a way for the plugin to read the project name, as opposed to the product name(which by default is listed as "Donation" by the WCQD plugin)?

**Comment by kkotha82** [comment]
Is it possible to have 2 extra mandatory billing user fields "Nationality" and "Passport/PAN Number" at checkout? These inputs should be saved against the user, and whenever the user logs in for another donation, these details should automatically appear in the billing details at checkout.

**Comment by kkotha82** [comment]
Can we add multiple donation projects with different amounts to a single cart and checkout as a single order? So if I want to donate different amounts to different projects, I can do it in one checkout, as opposed to making multiple orders.

**Comment by kkotha82** [comment]
Can we have a reports tab, where a report can be generated for total donations per month, per financial year, and by project, as indicated in the attached image?

![screen shot 2015-11-03 at 5 03 27 pm](https://cloud.githubusercontent.com/assets/15326217/10907072/f52707bc-824c-11e5-9c48-af08f0c1da86.png)
