### ISSUE TITLE
Error when deleting orders.

### ISSUE THREAD

**Issue by macra** [technofreaky/woocomerce-quick-donation#21]
This error, "You do not have sufficient permissions to access this page." occurs when deleting orders from the orders listing.

**Comment by macra** [comment]
Orders/donations are able to be trashed from the individual donation details. However when trashed you are redirected to the regular Woocommerce orders list rather than the Quick Donations donations list.

**Comment by technofreaky** [comment]
@macra 

I am trying to fix the first issue
> This error, "You do not have sufficient permissions to access this page." occurs when deleting orders from the orders listing.

The wodpress default is to redirect to the same post type of the deleted post. this cannot be overide
> Orders/donations are able to be trashed from the individual donation details. However when trashed you are redirected to the regular Woocommerce orders list rather than the Quick Donations donations list.

**Comment by panvagenas** [comment]
@technofreaky 

Give me some time, I'm on it.

**Comment by technofreaky** [comment]
@panvagenas thanks :)

**Comment by panvagenas** [comment]
I'm sorry but can't help with this.

**Comment by technofreaky** [comment]
@macra 

The below misioned issue has been fixed in the latest commit. can you please check the same and update the status ? 

> This error, "You do not have sufficient permissions to access this page." occurs when deleting orders from the orders listing.

**Comment by macra** [comment]
It's no longer throwing the error, but updates to a blank page. The order is deleted however.
