### ISSUE TITLE
SIngle Donation

### ISSUE THREAD

**Issue by macra** [technofreaky/woocomerce-quick-donation#22]
While not a critical issue for the current site I'm using this plugin on, a possible feature I'd like is the ability to add more than just the one donation. At present if someone wants to make a donation on multiple projects they have to make(checkout) each donation individually. I think it would enhance the plugin to be able to add donations to more than one project at a time, and checkout/pay for them all at once. Especially if the donor is using a Credit Card as their CC company may charge a per transaction fee, and this may discourage them from donating to more than one project.

Keep up the great work on this plug-in Varun, you are providing excellent and prompt support, which in the Wordpress world is greatly appreciated. On a side not I also use your, Role Based Pricing plug-in on another website. 

Regards,

Macra.

**Comment by technofreaky** [comment]
Request For The Same in WP Support :+1: 
https://wordpress.org/support/topic/multiple-donations?replies=4

**Comment by technofreaky** [comment]
@macra 

this feature cannot be done for now :( because there some core modification for this sorry
