### ISSUE TITLE
Error message when save changes

### ISSUE THREAD

**Issue by bondchester** [technofreaky/woocomerce-quick-donation#24]
Quick Donation -> Setting Page -> "Save Changes"

Warning: Cannot modify header information - headers already sent by (output started at /wordpress/wp-content/plugins/woocomerce-quick-donation-master/includes/admin/settings/validate-general.php:7) in /wordpress/wp-includes/pluggable.php on line 1207

**Comment by technofreaky** [comment]
@bondchester 
I have checked many times but i am not gettings this error. can you tell me the steps ?

**Comment by bondchester** [comment]
1) Fresh Install Wordpress
2) Upload Plugin & Activate

When I get sometime this week I'll check out the source code and implement the checking routine.

**Comment by technofreaky** [comment]
Hi,
Yesterday I have pushed latest source to github. In which it checks for WC
activation. Kindly can you check the Same issue with the latest source if
possible?

On Thu, Oct 29, 2015 at 11:33 am, David Huang < notifications@github.com [notifications@github.com] > wrote:
1) Fresh Install Wordpress
2) Upload Plugin & Activate

When I get sometime this week I'll check out the source code and implement the
checking routine.

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/24#issuecomment-152086024] .[https://github.com/notifications/beacon/ABzAfx1MV9DPFYZCMIdkwZnP2rrodpVaks5pAa5OgaJpZM4GXAhe.gif]

**Comment by technofreaky** [comment]
@bondchester as there is no reply from your side. i am closing this issue now. :)
