### ISSUE TITLE
Overwrites existing shopping cart names.

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#28]
Adding a donation to a cart with non-donation items (i.e. items form online store) breaks the whole cart.

All items in cart are labelled [Project Name], regardless if they are a donation, a coffee mug or a tshirt. 

Checkout button also renamed to "Donate Now"

This is no good!
![screen shot 2015-10-28 at 5 18 08 pm](https://cloud.githubusercontent.com/assets/12400683/10803342/1744cd98-7d98-11e5-9482-6e9762c7db9a.png)

**Comment by technofreaky** [comment]
Fixed And Updated In Github.
