### ISSUE TITLE
Integration For WooCommerce PDF Invoices Packing Slips Required

### ISSUE THREAD

**Issue by technofreaky** [technofreaky/woocomerce-quick-donation#29]
Reporter : @kkotha82 
> The donation 'project name' is not the same as WooCommerce 'product name'. I am using a plugin for generating PDF invoices(https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips). Is there a way for the plugin to read the project name, as opposed to the product name(which by default is listed as "Donation" by the WCQD plugin)?

Request Link : https://github.com/technofreaky/woocomerce-quick-donation/issues/2#issuecomment-151215299

**Comment by kkotha82** [comment]
The plugin used to work before the current update. Now it doesnt work at all. When I click the "generate invoice" button, I get an error: Fatal error: Can't use method return value in write context in /home/bluec6g4/public_html/wp-content/plugins/woocommerce-quick-donation/includes/class-quick-donation-process.php on line 123

**Comment by kkotha82** [comment]
<b>Edit to the above:</b> The plugin is broken now. It is not working at all. As a donor, when I login, the page does blank and I am getting just the one line error as stated above.

**Comment by technofreaky** [comment]
@kkotha82 will check for the issue and fix it. then i will work for the plugin integration

**Comment by kkotha82** [comment]
Awesome. Thank you! :)
