### ISSUE TITLE
Current Master Fatal Error

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#33]
Installing current master branch results in:

Fatal error: Can't use method return value in write context in /home/content/37/9036137/html/wp-content/plugins/woocomerce-quick-donation-master/includes/class-quick-donation-process.php on line 123

**Comment by technofreaky** [comment]
@benjamieson 
can i please know the steps to reproduce this error. and a screen of this is required

**Comment by benjamieson** [comment]
Step 1: Download Master Branch & Install
Step 2: Activate Plugin
Step 3: Sit is broken.
![screen shot 2015-10-30 at 9 53 48 am](https://cloud.githubusercontent.com/assets/12400683/10847346/256d0fca-7eec-11e5-9b03-f93bed69857b.png)

**Comment by technofreaky** [comment]
@benjamieson 
Can you please tell me the list of plugins you installed ?

**Comment by technofreaky** [comment]
@benjamieson can you please download the latest source from github and try once. i have fixed it

**Comment by kkotha82** [comment]
Latest source downloaded and installed. Now the error says: <b>Parse error: syntax error, unexpected '.', expecting ')' in .../plugins/woocommerce-quick-donation/includes/class-quick-donation-process.php on line 187</b>

**Comment by technofreaky** [comment]
@benjamieson sorry. again fixed the same. if you don't mind can you give a try  ?

**Comment by benjamieson** [comment]
This issue appears resolved.

**Comment by benjamieson** [comment]
Thanks. I have another one though! (will open separate ticket)

**Comment by technofreaky** [comment]
ok.. @benjamieson thanks for your continues support :)
