### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#34]
Have settings set to:

- Redirect to: Checkout Page
- Donation Exists: Checkout Page

On submitting donation, no redirect occurs, and an empty notification panel displays.

![screen shot 2015-10-30 at 10 16 34 am](https://cloud.githubusercontent.com/assets/12400683/10847880/749fb9e6-7eef-11e5-8e02-d375df2c33e0.png)
![screen shot 2015-10-30 at 10 15 30 am](https://cloud.githubusercontent.com/assets/12400683/10847881/74b0baac-7eef-11e5-8545-6be1ad746f91.png)

**Comment by technofreaky** [comment]
@benjamieson kindly try updating error message in settings then try again

**Comment by benjamieson** [comment]
Ahhh, you've killed the ability to buy form a store AND donate in one cart?

Uggh. That's kind of needed.

**Comment by technofreaky** [comment]
you can't add product + donation in a single cart

**Comment by benjamieson** [comment]
OK. It was possible previously. Will that functionality be restored?

**Comment by technofreaky** [comment]
@benjamieson i think you are aware of **BETA** version. and its not possible. to restore. because donation should be done as a seperate order not in a single order with products. i think you may understand
