### ISSUE TITLE
Error Displayed after adding donation

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#35]
Adding a donation and being redirected to checkout page shows the following PHP Warning at top of page:

Warning: Missing argument 2 for WooCommerce_Quick_Donation_Functions::wc_page_endpoint_title() in /home/content/37/9036137/html/wp-content/plugins/woocomerce-quick-donation-master/includes/class-quick-donation-functions.php on line 71

![screen shot 2015-10-30 at 10 46 16 am](https://cloud.githubusercontent.com/assets/12400683/10848677/7d60a672-7ef3-11e5-8749-e5e1b4c5d6c0.png)

**Comment by technofreaky** [comment]
@benjamieson i am not able to replicate the issue here. can you please give me a debug info. kindly copy the support info from 
**WooCommerce => System Report Page **

**Comment by benjamieson** [comment]
Will try to get to this today.
