### ISSUE TITLE
Donations in cart link to a 404 (Add Notice To Update Permalink When Donation Archive Not Working)

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#36]
Donation links in the cart need to link to the project page, not a 404 error.

If this can't be done, the link needs to be disabled on the cart page.

**Comment by technofreaky** [comment]
@benjamieson.. kindly . provide some for info.

**Comment by benjamieson** [comment]
Step one: Add a donation.

Step 2: View your cart

The donation is in the cart. The donation name is a link.

Clicking the link throws a 404.

<img width="1092" alt="screen shot 2015-10-30 at 6 59 58 pm" src="https://cloud.githubusercontent.com/assets/12400683/10859941/a1a85ba2-7f38-11e5-8158-b707ea1806db.png">
<img width="1048" alt="screen shot 2015-10-30 at 1 24 28 pm" src="https://cloud.githubusercontent.com/assets/12400683/10859942/a367098e-7f38-11e5-90d0-2d86b2d0d5b8.png">

**Comment by benjamieson** [comment]
(should show whatever you've content you've created for that 'project'

**Comment by technofreaky** [comment]
@benjamieson cany you give the link where you get the 404 error ?

**Comment by benjamieson** [comment]
https://breef.org/

Step 1: Make a donation (Right hand header)

Step 2: Click on "Cart" icon.

Step 3: Click on item (donation) in cart.

Result is a 404.

**Comment by technofreaky** [comment]
@benjamieson Kindly update permalink settings once and try again.

**Comment by benjamieson** [comment]
Done the update.

Now the description in the cart is renamed "Cart" which is very bad (it should be named at least with the name of the project), and links to the cart - again - not good.

<img width="966" alt="screen shot 2015-11-01 at 9 09 15 am" src="https://cloud.githubusercontent.com/assets/12400683/10869287/6fff77f2-8078-11e5-868b-c6152255049f.png">

**Comment by technofreaky** [comment]
@benjamieson can you please contact me over my email to get this resolved 
varunsridharan23@gmail.com

**Comment by technofreaky** [comment]
@benjamieson i checked the issue in your site but its perfectly working in your site :)

**Comment by technofreaky** [comment]
@benjamieson as there is no reply from your side i am closing this issue now :) if you still have the same issue. you can reopen this or create a new issue at any time :)

**Comment by benjamieson** [comment]
Apologies - have been away. Issue seemed to only affect donations in the cart at upgrade time.
