### ISSUE TITLE
Thank you page after donation shows "donation" instead of project name

### ISSUE THREAD

**Issue by kkotha82** [technofreaky/woocomerce-quick-donation#37]
After donation, the thank you page shows "donation" instead of project name under order details. Screenshot attached.

![thank-you-page](https://cloud.githubusercontent.com/assets/15326217/10851536/a3110ef8-7f51-11e5-9be4-885e51f54050.png)

**Comment by technofreaky** [comment]
@kkotha82  can you please check for the issue with latest source and update the status here ?
