### ISSUE TITLE
Orders in admin problems

### ISSUE THREAD

**Issue by ierpe** [technofreaky/woocomerce-quick-donation#40]
Hey Varun,

I noticed a couple of problems while viewing and deleting orders from the admin interface :

- While listing donations, if I click on the view button of a donation, it's the WooCommerce menu that opens instead of the WCQD menu

- When I'm viewing a donation, I can move it to the trash. I can see it in the donation trash alright, but in the WooCommerce orders, I see the trash number counting the trashed donations, although they do not appear in the list

- From the donations, I can trash some donations in a bulk, but I land on a blank page (but the donations are successfully trashed). Same thing happens when I restore the trashed donations, or when I permanently delete the trashed donations

- In the donation list, in the project column, I get stuff like : "Order – novembre 3, 2015 @ 06:38", because I did not create any project. This link has the format : http://mysite.com/fr/?post_type=shop_order&p=8767
When I click on it, I get a 404
Same thing when I view the order, this link appears and links to a 404 page.

**Comment by technofreaky** [comment]
@ierpe 
thanks for reporting the issue. but those all are takes different time and will be fixed in different release. so what i do is . i will create separate issue for each . so that it help to get keep tracked

**Comment by ierpe** [comment]
@technofreaky yes of course you're right.
I will also have a look and make pull requests if I find solutions.

**Comment by technofreaky** [comment]
@ierpe thanks :)
