### ISSUE TITLE
Automatic confirmation email not sent when donation made through payment gateway

### ISSUE THREAD

**Issue by kkotha82** [technofreaky/woocomerce-quick-donation#45]
When I make a new donation using <b>cheque/DD method</b>, the status of the donation is <b>"on-hold"</b>, I am getting the automatic confirmation email in this scenario.

But, when I make a donation using <b>payment gateway</b>, the status of the donation is <b>"processing"</b>. I am not getting the automatic confirmation email in this scenario.

Kindly fix this issue.

**Comment by technofreaky** [comment]
@kkotha82  i have fixed this issue and also added 2 new emails (Complete & Processing) kindly check for the same with latest source
