### ISSUE TITLE
After bulk deleting (move to trash), blank page is coming up

### ISSUE THREAD

**Issue by kkotha82** [technofreaky/woocomerce-quick-donation#48]
After selecting bulk donations, and clicking on move to trash, the page is reloading and blank page is showing up. Can it refresh and reload the donations page instead?

**Comment by technofreaky** [comment]
@kkotha82 this is marked as Duplicate as this issue is already reported #43.
Kindly download the latest source from here and try once . this issue has been fixed. :)
