### ISSUE TITLE
Critical: Update to latest kills admin area

### ISSUE THREAD

**Issue by benjamieson** [technofreaky/woocomerce-quick-donation#58]
Updated via Wordpress.com to 1.3.7.

Can no longer access the administration of WP. Following error is given:

Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/content/37/XXXXXXXX/html/wp-content/plugins/woocommerce-quick-donation/includes/admin/class-admin-functions.php on line 134

followed by a blank page.

No projects appear on donations widget in header:

    https://breef.org/

Please help.

**Comment by benjamieson** [comment]
![screen shot 2015-11-09 at 1 27 16 pm](https://cloud.githubusercontent.com/assets/12400683/11042529/a68f9c70-86e5-11e5-944e-0b630a770f1e.png)

**Comment by benjamieson** [comment]
The screenshot above is after:

1: Deleting WCQD via FTP
2: Downloading master branch here
3: Plugins » Add New » Upload from wp-admin
4: Activate Plugin

**Comment by benjamieson** [comment]
NOTE:

In PHP T_PAAMAYIM_NEKUDOTAYIM is the token name for ::, the static separator. It’s Hebrew for double colon.

**Comment by technofreaky** [comment]
hi,

I am really sorry for the inconvenience.

let me fix and release a fix version

**Comment by technofreaky** [comment]
@benjamieson. could you please send me the access to check ? i  checked in my local. its fine. may be some php core version changes. so i need to check

**Comment by technofreaky** [comment]
@benjamieson can you please download V 1.3.7.1 and check

**Comment by benjamieson** [comment]
Exactly the same issue.

I tried 

1: Disabling all plugins
2: Activating WCQD - activation is fine
3: ReActivating WooCommerce: Parse Error immediately.

This is a live site, and the client depends on it for their charity, so I can't do any more random tests that break everything, unfortunately.

**Comment by technofreaky** [comment]
@benjamieson can you please conme to online chat ?
https://www.hipchat.com/gVcsNs3aC
