### ISSUE TITLE
Media Library Doesn't Display When Plugin Active

### ISSUE THREAD

**Issue by Blackhawke** [technofreaky/woocomerce-quick-donation#60]
Okay, I added a comment over on the blank page bug, but the plugin is creating another problem as well, and it's system wide: With the plugin active, the media library is broken. I can't upload images, and it won't display the images already in the library either. When I disable the plugin (which I have), the image library works fine again.

(Running WP 4.3.1)

**Comment by kkotha82** [comment]
@Blackhawke Did you try and deactivate your current theme, to see if it is causing a conflict? My theme created quite a few conflicts with this plugin, which I managed to resolve with custom code. But I did not have this issue you are having.

**Comment by Blackhawke** [comment]
No I didn't. That's good to know, but disappointing. We're running 40 plugins, and all of them play nice except this one. I'm rather surprised too, as it's a Wootheme. Still... Everybody can't be out of step except Johnny, as it were. :P

**Comment by technofreaky** [comment]
@Blackhawke hi
thanks for using my plugin.. i have also checked in my local but i can't find the issue.
so i would like to check the issue in your setup. i kindly request you to provide admin access to check for the issue :)

please send the login info via email : varunsridharan23@gmail.com

**Comment by technofreaky** [comment]
@Blackhawke No update from you ?

**Comment by Blackhawke** [comment]
Hey! I sent you the login information via the email above 2 days ago. Did you not get it?

**Comment by Blackhawke** [comment]
Okay... Just got the update notice. Re-enabled the plugin after updating and it *seems* to be working okay now. No more media library problems, and no more blank pages after saving, and all that jazz.

So... So far, so good. You through nosing around our site? :)

**Comment by technofreaky** [comment]
Cool :) nice
