### ISSUE TITLE
Quick add donation without project selection

### ISSUE THREAD

**Issue by kkotha82** [technofreaky/woocomerce-quick-donation#61]
Let us say if my project id no. 26 is a project called "educate a child". On my homepage, let us say I write a content for educate child, and below that I put our shortcode like [wc-quick-donate id="26"]. Only the amount and Donate button should appear, since the plugin already knows what project id=26" is. When i input an amount, and hit donate, it is automatically added to the cart, with project name "educate a child"
and the amount I selected. Screenshot attached for a better understanding.

![screen shot 2015-11-13 at 11 29 46 am](https://cloud.githubusercontent.com/assets/15326217/11139941/3b68c4ee-89fb-11e5-9315-ac3ebc373ccd.png)

**Comment by technofreaky** [comment]
Added Feature And Updated in Github
