### ISSUE TITLE
WooCommerce Mini Cart Widget being overwritten on shop page

### ISSUE THREAD

**Issue by ierpe** [technofreaky/woocomerce-quick-donation#65]
On my shop page, when I add the WC cart widget on the sidebar, it is using the template from
``` plugins/woocommerce-quick-donation/template/cart/donation-mini-cart.php ```
instead of
``` themes/mytheme/woocommerce/cart/mini-cart.php ```

My site has a WC shop and the WCQD pluign... Is it possible to display the "donation cart" only on some specific page / sidebar ?

**Comment by BurlesonBrad** [comment]
@ierpe There are several options for this.  You can either hard code some conditional rules so that only certain widgets are displayed on certain pages.  However a better solution might be to use a plugin so that you can customize these options much easier:
https://www.google.com/search?num=20&q=show+widget+on+specific+page

**Comment by ierpe** [comment]
Hey Brad, thanks for your answer!

I probably explained myself a bit wrong here.
The thing is, on my shop page(s), like the main products page or the single product page of WooCommerce (and not WC Quick Donation), the mini cart template that is being used is : 
``` plugins/woocommerce-quick-donation/template/cart/donation-mini-cart.php ```
or
``` themes/mytheme/woocommerce/donation/cart/donation-mini-cart.php ```

When it should be, in my opinion, using the template
``` plugins/woocommerce/templates/cart/mini-cart.php ``` 
or
``` themes/mytheme/woocommerce/cart/mini-cart.php ``` 

Do you see what I'm getting at?
The template for the WC shop pages should not be using the WCQD donation mini cart template, at least not on the WC pages.
Somehow it should be a different Widget all together for WCQD, but right now when you add the WC cart widget in a sidebar, you're getting the WCQD mini cart widget template... know what I mean?

**Comment by technofreaky** [comment]
@ierpe 
sorry i think its a code mistake in my plugin. let me check and solve this and update here. thanks for reporting the bug here

@BurlesonBrad Thanks for your contribution :)

**Comment by technofreaky** [comment]
Fixed And Updated in github
