### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by efficience** [technofreaky/woocomerce-quick-donation#67]
Hi

Thanks a lot for your plugin, it's great !

I've only got one little problem with the language. I need it in french, but the language doesn't change it's always in english.
I made a lot of tests but without success.
Maybe a problem with public function load_plugin_mo_file ?

Thanks
Regards
Regis

**Comment by bastienho** [comment]
I figure the same issue.
I tried to copy the files with native WordPress structure

- woocommerce-quick-donation-fr_FR.mo
- woocommerce-quick-donation-fr_FR.po

and commnt the filter relative to text domain... bu nothing. 

Maybe `plugins_loaded` hook is too late for loading a textdomain ?

**Comment by jan1980** [comment]
Hi guys,

As a temporary fix, could it work if we add the translatable strings to the WooCommerce .po language files themselves?

Cheers,

**Comment by technofreaky** [comment]
@jan1980 
@bastienho 
@efficience 

I am sorry for the delay.

I have just fixed the language issue. can you please download the latest version from here and please check it out ?

**Comment by jan1980** [comment]
Excellent, many thanks!
Best regards,
