### ISSUE TITLE
Adding a donation does not redirect to cart/checkout if one already exists in users cart.

### ISSUE THREAD

**Issue by bgallagh3r** [technofreaky/woocomerce-quick-donation#7]
I am working with a site (WP ~4.2 and WooCommerce 2.3.11) where we have set WCQD to empty items and redirect to checkout page, and also to hide the donation form if a donation already exists.

If a user has a donation in their cart, and they return to the donate form it should not display at all, instead should give them a link to go to the currently set redirect page, or cart by default, but it doesn't.

On top of that, if the user adds another donation regardless if "Remove Previous Items" is set in the WCQD settings, the form submits but no longer redirects directly after.  Upon going to the cart page a number of notices appear.   My guess is that the notices are preventing the redirect.

I haven't had the time to look into this issue myself in any depth but thought it should be made known.

**Comment by technofreaky** [comment]
Fixed Updated in Github
