### ISSUE TITLE
Price changes to "FREE" ...Please advice

### ISSUE THREAD

**Issue by restyles4** [technofreaky/woocomerce-quick-donation#73]
Using Woo with typical variable product setup. 6 donation choices. Used product sku from auto creation on install. Trying to help an important non-profit use your plug-in. Please advice ASAP.

Thank You,
RE

**Comment by technofreaky** [comment]
@restyles4 
Really sorry.. i can't understand what you are trying to say. can you please explain it :?

**Comment by restyles4** [comment]
https://www.dropbox.com/s/q1q76yp6h57f1id/20160103_015700.mp4?dl=0

**Comment by technofreaky** [comment]
Will check and get back to as soon as possible

You can contact me via my email

Varunsridharan23@gmail

On Sun, Jan 03, 2016 at 12:45 pm, restyles4 < notifications@github.com [notifications@github.com] > wrote:
https://www.dropbox.com/s/q1q76yp6h57f1id/20160103_015700.mp4?dl=0
[https://www.dropbox.com/s/q1q76yp6h57f1id/20160103_015700.mp4?dl=0]

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/73#issuecomment-168471623] .[https://github.com/notifications/beacon/ABzAf5zPjEDtaXNG1bH-4ueQvUhYF6V-ks5pWMIQgaJpZM4G9qdC.gif]

**Comment by restyles4** [comment]
Thought this also might help. System Info Video:
https://www.dropbox.com/s/7cloo8zjmunahb0/20160103_021821.mp4?dl=0

Thanks...appreciate anything you can do...

RE

**Comment by restyles4** [comment]
### Begin WooCommerce Quick Donation Status ###

-- WordPress Environment

Home URL:                 https://hairheroes.foundation
Site URL:                 https://hairheroes.foundation
WP Version:               4.4
WP_DEBUG:                 Disabled
WP Language:              en_US
Multisite:                No
WP Memory Limit:          40MB
WP Memory Limit Status:   Not OK - Recommended Memory Limit is 64MB
WP Table Prefix:          ElVqNmCE
WP Table Prefix Length:  8
WP Table Prefix Status:   Acceptable
WP Timezone:              , GMT: 0
WP Remote Post:           wp_remote_post() works
Permalink Structure:      /%postname%/
Registered Post Stati:    publish, future, draft, pending, private, trash,
auto-draft, inherit, donation-completed, donation-on-hold,
donation-refunded, charitable-pending, charitable-completed,
charitable-failed, charitable-cancelled, charitable-refunded,
charitable-preapproved, wc-pending, wc-processing, wc-on-hold,
wc-completed, wc-cancelled, wc-refunded, wc-failed
Show On Front:            posts

## Theme Information ##

Theme Name:               Pinnacle
Theme Version:            1.3.4
Theme Author:             Kadence Themes
Theme Author URI:         http://www.kadencethemes.com/
Is Child Theme:           No

## Plugins Information ##


-- Must-Use Plugins

: {V :  || A :  }

-- WordPress Active Plugins

All In One WP Security : {V : 4.0.3 ||  A : Tips and Tricks HQ, Peter,
Ruhul, Ivy }
http://www.tipsandtricks-hq.com/wordpress-security-and-firewall-plugin
Charitable : {V : 1.2.4 ||  A : WP Charitable } https://www.wpcharitable.com
Custom Referral Spam Blocker : {V : 1.0.4 ||  A : csmicfool }
http://jacobbaron.net/
Donately Integration : {V : 5.0.0 ||  A : Fifty & Fifty }
http://www.donately.com
Easy Forms for MailChimp by YIKES : {V : 6.0.3.7 ||  A : YIKES }
http://www.yikesinc.com/services/yikes-inc-easy-mailchimp-extender/
Google Analytics by Yoast : {V : 5.4.6 ||  A : Team Yoast }
https://yoast.com/wordpress/plugins/google-analytics/#utm_source=wordpress&utm_medium=plugin&utm_campaign=wpgaplugin&utm_content=v504
Huge IT Image Gallery : {V : 1.7.4 ||  A : Huge-IT }
http://huge-it.com/wordpress-gallery/
McAfee SECURE : {V : 1.0 ||  A : McAfeeSECURE }
https://www.mcafeesecure.com/
Responsive Menu : {V : 2.8.5 ||  A : Responsive Menu }
http://responsive.menu
SumoMe : {V : 1.10 ||  A : SumoMe } http://sumome.com
Virtue / Pinnacle ToolKit : {V : 3.2 ||  A : Kadence Themes }
WooCommerce : {V : 2.4.12 ||  A : WooThemes }
http://www.woothemes.com/woocommerce/
WooCommerce Quick Donation : {V : 1.3.8 BETA ||  A : Varun Sridharan }
http://wordpress.org/plugins/woocommerce-quick-donation/
WP Super Cache : {V : 1.4.7 ||  A : Automattic }
https://wordpress.org/plugins/wp-super-cache/
YITH WooCommerce Stripe : {V : 1.2.3 ||  A : YIThemes }
http://yithemes.com/themes/plugins/yith-woocommerce-stripe/
Yoast SEO : {V : 3.0.7 ||  A : Team Yoast }
https://yoast.com/wordpress/plugins/seo/#utm_source=wpadmin&utm_medium=plugin&utm_campaign=wpseoplugin
ZWoom - WooCommerce Product Image Zoom : {V : 1.2 ||  A : WisdmLabs, India
}
http://wordpress.org/extend/plugins/zwoom-woocommerce-product-image-zoom-extension-by-wisdmlabs/

-- WordPress Inactive Plugins

Akismet : {V : 3.1.6 || A : Automattic } http://akismet.com/
All In One SEO Pack : {V : 2.2.7.5 || A : Michael Torbert }
http://semperfiwebdesign.com
Constant Contact Forms by MailMunch : {V : 2.0.4 || A : MailMunch }
http://connect.constantcontact.com/integrations/mailmunch-email-list-builder
Gallery Bank Lite Edition : {V : 3.0.449 || A : Tech Banker }
http://tech-banker.com
Online Payments with PayPal and Stripe - By vCita : {V : 3.3.0 || A :
vCita.com } http://www.vcita.com
Theme Check : {V : 20151211.1 || A : Otto42, pross }
http://ottopress.com/wordpress-plugins/theme-check/

## Server Environment ##

Server Info:              Apache
Host:                     DBH: db605956338.db.1and1.com, SRV:
hairheroes.foundation
Default Timezone:         UTC
MySQL Version:            5.5.46-0+deb7u1-log

-- PHP Configuration

PHP Version:              5.5.30
PHP Post Max Size:        52428800
PHP Time Limit:           30
PHP Max Input Vars:       1000
PHP Safe Mode:            No
PHP Memory Limit:         256M
PHP Upload Max Size:      41943040
PHP Upload Max Filesize:  41943040
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes

-- PHP Extentions

DISPLAY ERRORS:           On (1)
FSOCKOPEN:                Your server supports fsockopen.
cURL:                     Your server supports cURL.
SOAP Client:              Your server has the SOAP Client enabled.
SUHOSIN:                  Your server does not have SUHOSIN installed.

-- Session Configuration

Session:                  Disabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:
Use Cookies:              On
Use Only Cookies:         On

-- Client Details:

Platform:                 Windows
Browser Name:             Firefox
Browser Version:          43.0
User Agent String:        Mozilla/5.0 (Windows NT 10.0; WO
 W64; rv:43.0) Gecko/20100101 Fir
                          efox/43.0

Client IP Address:        198.11.221.137

## WC Qucik Donation Settings Information ##

Simple Donation Product Exist : 1

 -- general Settings
wc_qd_redirect_user : checkout
wc_qd_already_exist_redirect_user : cart
wc_qd_payment_gateway : ["yith-stripe","cheque"]

 -- message Settings
wc_qd_empty_donation_msg_1 : null
wc_qd_donation_with_other_products : Unable To Process Donation. Kindly
Complete The Exist Order
wc_qd_empty_donation_msg : Please Enter A Donation Amount
wc_qd_donation_already_exist : Donation Already Exist In Cart. Kindly
Complete The Existing
wc_qd_invalid_donation_msg : Invalid Donation Amount Entered
[{donation_amount}]
wc_qd_min_rda_msg : Please Enter Minimum of {min_amount}.
wc_qd_max_rda_msg : Please Enter Maximum of {max_amount}.

 -- shortcode Settings
wc_qd_default_render_type : select
wc_qd_shortcode_show_errors : true
wc_qd_pre_selected_project : 445
wc_qd_pre_defined_amount : 20|40|60|80|100|200|400|800|1000

## Template Override Information


### End WooCommerce Quick Donation Status ###

**Comment by technofreaky** [comment]
@restyles4 

you should use the below shortcode
`[wc-quick-donation]`

you should not view the product page of donation

if you need me to set it up for you. please contact me via email

**Comment by restyles4** [comment]
I tried the short code in every conceivable place possible. Product, tag,
category on both sides of plug-ins. In yours under project which seems to
not go anywhere functionally, and also on Woos under product.

Your "Quick Donation" plug-in product entry install file doesn't' seem to
fully follow over to Woocommerce product. I'm assuming that your plug-in
Cat and Tags are for "Projects" under your your plug-in only.

Yes,,,please help install. I have about 10 hours into this already. I'll be
dam if I'm gonna throw it all away without resolve.

Thank You,,,please advise..

RE

**Comment by technofreaky** [comment]
@restyles4 
Please contact me via skype. so that i can help you more on this.

Skype ID : varunsridharan23
