### ISSUE TITLE
woocomerce-quick-donation - How to

### ISSUE THREAD

**Issue by Finjas** [technofreaky/woocomerce-quick-donation#74]
I have installed this plugin but can not seem to get it to work.

I'm new to Wordpress. I created a new page and inserted the shortcode. If I run the page I get only th option to enter the amount and then click on the donate button. Then nothing happens.

Could you help please

**Comment by technofreaky** [comment]
@Finjas 

after you install this plugin. you will have a new menu in admin menu bar, in the name of " Quick Donation :) "

First you need to configure the project and then you can use the Shortcode.

if you need i can set it up for you. but it will be chargeable @ 25USD Pre request

**Comment by Finjas** [comment]
Thanks for the reply.

 

I have seen “Quick Donation” option, and has configured the project before I contacted you. I must be doing something wrong .

 

Do you have any documentation regarding the configuration of the project?

**Comment by technofreaky** [comment]
Check this
http://wordpress.org/plugins/woocommerce-quick-donation/
