### ISSUE TITLE
error messages not displaying 

### ISSUE THREAD

**Issue by frenzyrid11** [technofreaky/woocomerce-quick-donation#8]
I am using the plugin on my website.
If I submit the form without entering any amount, or without selecting any project, the page redirects to itself and does not display the error messages. In fact it displays those error messages on the Cart page.
I need this fixed as soon as possible.

**Comment by technofreaky** [comment]
Hi,

Can i get the error message so that i can check what is the issue. if possible kindly add screenshot

**Comment by frenzyrid11** [comment]
Hi,

What i mean to say is, if i submit the empty form, the errors stack on the cart page, but the users have no way of knowing they occur, the user is redirected to same page (donation) only.

**Comment by nitiresources** [comment]
This issue reported by @frenzyrid11 is still not solved. Please can @technofreaky it be attended to urgently?

**Comment by technofreaky** [comment]
@nitiresources  sorry for the inconvenience caused.  can i know where did you called the shortcode 

in a page / post / php template file  ?

**Comment by nitiresources** [comment]
In a Page

**Comment by nitiresources** [comment]
Hi @technofreaky. Are you doing anything about it? I called the shortcode in a page and the moment I have attempted donating, the next attempt does not work until I clear my cache.

**Comment by technofreaky** [comment]
@nitiresources  can you please come online chat for few min to get this resolved if you dont min ?

Chat Link : https://technofreaky.campfirenow.com/89dd8

**Comment by nitiresources** [comment]
Hi Varun

This is the link to plugin. The first donation should redirect to checkout
page but the second will not. This means, if someone made a mistake in the
first and want to correct it before make the donation, he would not.

This is the second website I am using your plugin and its the same issue.

Thanks for attending to this issue.

Ezekiel

**Comment by technofreaky** [comment]
Hi,

I have checked it and fixed too. will sure release it 1 day. its under testing

**Comment by nitiresources** [comment]
Great effort. Waiting

**Comment by technofreaky** [comment]
Released a new version https://wordpress.org/plugins/woocommerce-quick-donation/
will soon update the code in github

**Comment by technofreaky** [comment]
This issues fixed :)
