### ISSUE TITLE
"Projects" in WPML plugin (WordPress Multi Language)

### ISSUE THREAD

**Issue by jan1980** [technofreaky/woocomerce-quick-donation#83]
Many thanks for this nice plugin.

I noticed that when using WPML, once we make the Projects translatable, the Submit Donation Form display all projects from all languages (as "options" to select from).

However, only the current language would need to be displayed.
Is there something we can add to fix it?

Many thanks for any guidance,

**Comment by technofreaky** [comment]
@jan1980 

Still our plugin is not yet stable. we are trying to make it more stable. and later we decided to make it compatable with WPML. 

i am looking for some good contributors how can really test and provide us some info on bugs, provide some idea on new features. and more

**Comment by jan1980** [comment]
I fixed it by using the single donation shortcode instead, on each translated page, using the correspondent donation / project ID.
I can provide feedback for WPML (will open a new ticket for a certain issue).
