### ISSUE TITLE
I want to change Drop down Text "Select A project" to different language

### ISSUE THREAD

**Issue by rakib32** [technofreaky/woocomerce-quick-donation#9]
Hi,

Can you add a feature so that we can change the text "Select A project" to different text :)

**Comment by technofreaky** [comment]
Hi,

Really sorry for the delay. in current version its not possible. i am working on a new version. for that i need few tester's can you contribute your time for testing and improving the plugin ?
if yes kindly contact me via varunsridharan23@gmail.com / plugin@varunsridharan.in
